name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '18' 

      - name: Install npm dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build your web application
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          # Determine the Firebase Hosting Chanel based on the branch name 
          if ["${{ github.ref}}" = "refs/heads/master"]; then
            CHANNEL = "master"
          else
            if ["${{ github.ref}}" = "refs/heads/dev"]; then
            CHANNEL = "dev"
          else
            # if the branch is not master or, exit without deploying
            echo "Branch not set up for develployment."
            exit 0
          fi
          # Deploy your application to the spercified Hosting Chanel
          firebase hosting:chanel:deploy"$CHANNEL" --token "$ABIDE_IN_CHRIST"
        env:
          FIREBASE_TOKEN: ${{ secrets.ABIDE_IN_CHRIST }}
